# Generated by Django 4.1.4 on 2022-12-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_main_page_portfolio_picture_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
