# Generated by Django 4.1.4 on 2022-12-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
