# Generated by Django 4.1.4 on 2022-12-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_accs',
        ),
    ]
